go-zookeeper/zk

lock.go

LockWithData is a new method that allows creating a lock with a
specified content. This helps in scenarios where it's necessary to
correlate data to a lock, e.g. multiple systems contending a lock
and needing to know which one got it.
Signed-off-by: Andrea Barberio <insomniac@slackware.it>

Add Lock.LockWithData

---

.travis.yml

A bit of a temp hack from changes in the travis ecosystem. gets us tests running again.

travis : fix the build command that is not present anymore

---

lock.go
lock_test.go

I got the following error message while using the library:
```
strconv.Atoi: parsing \"640f65557dc046648b51a144f37fc95d__lock__0000196658\": invalid syntax"
```
Which led me to finding https://github.com/python-zk/kazoo/issues/548.
Apparently the Go and Python client libraries use a different prefix and don't work well with each other.
I haven't tested the PR yet. I am putting it up for comments to see if it makes sense.

[lock] interoperate with Python client

---

.github/workflows/unittest.yaml

I was getting the following error:
```
Please provide an upload token from codecov.io with valid arguments
```
From https://github.com/codecov/codecov-action
```
For public repositories, no token is needed
```
Fixes #20

remove codecov token

---

.codecov.yaml
.github/workflows/unittest.yaml
flw.go
structs.go

* bump ZooKeeper, Go and Java versions
* pass ZK_VERSION when running tests
* FLW latency average can be a float instead of an int
* Update codecov project threshold

bump versions

---

cluster_test.go

From the [docs](https://zookeeper.apache.org/doc/r3.6.1/zookeeperProgrammers.html):
> If it is important that Client A and Client B read the same value, Client B should call the sync() method from the ZooKeeper API method before it performs its read.
This is an attempt to fix one of the flaky tests mentioned in #17:
```
--- FAIL: TestBasicCluster (11.20s)
##[error]    cluster_test.go:15: [ZKERR] ZooKeeper JMX enabled by default
##[error]    cluster_test.go:15: [ZKERR] ZooKeeper JMX enabled by default
##[error]    cluster_test.go:15: [ZKERR] ZooKeeper JMX enabled by default
##[error]    cluster_test.go:15: [ZKERR] Using config: /tmp/gozk770506775/srv3/zoo.cfg
##[error]    cluster_test.go:15: [ZKERR] Using config: /tmp/gozk770506775/srv2/zoo.cfg
##[error]    cluster_test.go:15: [ZKERR] …
```

cluster_test: add sync

---

conn.go

All other events are published to the global event callback; but lost session events are not.  These events are essential to correctly implement cross-cutting wrapper frameworks that do things like re-add watches when a new session is obtained.

Global EventNotWatching events for session lost

---

flw.go

```go
func BenchmarkCompare(b *testing.B) {
var response = []byte("imokres")
b.Run("1", func(b *testing.B) {
b.ReportAllocs()
for i := 0; i < b.N; i++ {
if bytes.Equal(response[:4], []byte("imok")) {
}
}
})
b.Run("2", func(b *testing.B) {
b.ReportAllocs()
for i := 0; i < b.N; i++ {
if string(response[:4]) == "imok" {
}
}
})
}
```
```
cpu: Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz
BenchmarkCompare
BenchmarkCompare/1
BenchmarkCompare/1-4 	195669936	         5.736 ns/op	       0 B/op	       0 allocs/op
BenchmarkCompare/2
BenchmarkCompare/2-4 	1000000000	         0.2531 ns/op	       0 B/op	       0 allocs/op
PASS
```

Optimize comparison

---

conn.go

The  pull comes as the help of the issue #4 . If you guys see it O.K., I'll continue to add other missing comments. FYI, I'm happy to participant in an Open Source project. Thanks for your time.

[doc] add some go doc in conn.go

---

conn.go
conn_test.go

In accordance with
https://github.com/apache/zookeeper/blob/c74658d398cdc1d207aa296cb6e20de00faec03e/zookeeper-client/zookeeper-client-c/src/zk_hashtable.c#L297-L314
```c
switch(type){
case CREATED_EVENT_DEF:
case CHANGED_EVENT_DEF:
// look up the watchers for the path and move them to a delivery list
add_for_event(zh->active_node_watchers,path,&list);
add_for_event(zh->active_exist_watchers,path,&list);
break;
case CHILD_EVENT_DEF:
// look up the watchers for the path and move them to a delivery list
add_for_event(zh->active_child_watchers,path,&list);
break;
case DELETED_EVENT_DEF:
// look up the watchers for the path and move them to a delivery list
add_for_event(zh->active_node_watchers,path,&list);
add_for_event(zh->active_exist_watchers,path,&list); …
```

fix the set of events received by ChildrenW

---

lock.go
lock_test.go

This PR includes a change to the `parseSeq` function used by the lock to parse sequence numbers. When the Zookeeper sequence number rolls over it rolls to -2147483647 rather than 0. `parseSeq` splits on a "-" symbol so when the path is split into parts the negative symbol is stripped away incorrectly. I changed this to split on the full prefix of "lock-" instead which saves the negative symbol. A test for this is included.

Fix parseSeq incorrectly parsing negative sequence number

---

conn.go
conn_test.go
tcp_server_test.go

Fixes https://github.com/go-zookeeper/zk/issues/79
Instead of blindly waiting for a response from `queueRequest`, wait for a message on either the requests response channel or an indication that the client `shouldQuit`. This ensures that any ongoing requests are completed when a client is closed.

Fix deadlock caused by non-responsive ZK servers

---

.github/workflows/integration.yaml
.github/workflows/unittest.yaml
Makefile
cluster_test.go
conn_test.go
dnshostprovider_test.go
lock_test.go
server_help_test.go
zk_test.go

The tests that spin up a zookeeper cluster for testing are flaky in nature. They provide a great verification of behavior but are not isolated to Go. 
This leaves the tests in a state where they flake for various reasons outside of the control of the Go runtime.

break out tests that run a java zk cluster 

---

.gitattributes
cluster_test.go
server_help_test.go
zk_test.go

1.15 added https://pkg.go.dev/testing#T.TempDir
includes .gitattributes to ensure eol as LF

tests: use t.TempDir() for tests

---

.github/workflows/stale.yml

Github action to post when issues and PRs are stale. To start this has debug-only to see a dry run and adjust from the results.
https://github.com/actions/stale
first draft:
- issues are stale after 2 years, give 15 days before close. 
- PRs are 6 months stale (we want to rebase) and never closes. 
- debug-only (will not post anything)
- Exclude both from the milestone "v2" that we track.

Create stale.yml github action

---

constants.go

NOTE: WatcherEvent State will change from `StateUnknown` to `StateSyncConnected`
jeffbean: rebased authored commit from @KaithyRookie to pickup unit test configuration in github. 
StateSyncConnected means client is connected to a server in the ensemble

<fix>[constants]: add StateSyncConnected WatchEvent state

---

.codecov.yaml
.github/workflows/integration.yaml
.github/workflows/lint.yaml
.github/workflows/stale.yml
.github/workflows/unittest.yaml

1. action/stale: debug mode shows deprecation warning of older version. update to v9 (current latest)
2. integration_test and unittest workflows: update tiggers to prevent double trigger on PR update. 
3. action/codecov: update version, and settings for action.
4. action/codecov: if condition on the test matrix to only run on the first matric job, removing the upload to happen for each combo in the test matrix. 
5. codecov.yaml: update threshold to what we have now at 76%. also up the patch to 80%.

update github actions. cleanup and edits. 

---

zk_test.go

inspiration from https://github.com/go-zookeeper/zk/pull/88
cleanup up the logic. but the idea is to support the tests requiring a version of ZK based on the API support in ZK.

adding requireMinimumZkVersion test helper

---

conn.go
constants.go
create_mode.go
create_mode_test.go
structs.go
zk_test.go

BREAKING Client behavior: since this proposes a new parsing of the Create flag integer this will break clients if they rely on CreateContainer as it was creating znodes that may not have been containers.
Changes:
- Fix FlagTTL value from 4 -> 5
- Adding all known CreateMode values to Flag constants.
- Adding a createMode private struct behind the flag integer, replicate CreateMode from ZK java lib.
- Create, CreateContainer, CreateTTL methods now parse the flag integer passed in based on the constants defined (new error condition).
- Rewrite tests to better catch CreateContainer and CreateTTL (no assertions on zk behavior since zk does not expose znode mode)
- Added Change-Detector unit tests for create mode values.

[BC] CreateMode: refactor and fix FlagX Create flags. 

---

conn.go
dnshostprovider.go
dnshostprovider_test.go

Resolves #142 by adding a 3s timeout for DNS lookups. This is better behavior than having the call get stuck indefinitely when the DNS resolver isn't reachable.
Adjusted/added unit tests to verify.
```
$ go test -run ^TestNewDNSHostProvider$
PASS
ok      github.com/go-zookeeper/zk      0.207s
```

add dns host provider lookup timeout
